name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Build UI
        run: npm run build
        working-directory: vue-ui
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          toolchain: nightly
          components: rust-src
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
